spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/hello?useSSL=false
    username: root
    tomcat:
      max-active: 4
      max-idle: 4
      min-idle: 4
      initial-size: 4